### ISSUE TITLE
GuzzleHttp issue on local server

### ISSUE THREAD

**Issue by jmd-david** [XeroAPI/xero-php-oauth2-custom-connections-starter#1]
Hi, im testing these starter sample and manage to install it, add all the credentials and reached the **authorizedResource.php** page. But when i click on the link **Create one Contact** the below error shows

Anyone already encounter this issue? how did you fix it?

_Fatal error: Uncaught Error: Call to undefined function GuzzleHttp\Psr7\build_query() in D:\MAMP\htdocs\xero-php-oauth2-custom-starter\vendor\xeroapi\xero-php-oauth2\lib\Api\AccountingApi.php:4601 Stack trace: #0 D:\MAMP\htdocs\xero-php-oauth2-custom-starter\vendor\xeroapi\xero-php-oauth2\lib\Api\AccountingApi.php(4364): XeroAPI\XeroPHP\Api\AccountingApi->createContactsRequest('', Object(XeroAPI\XeroPHP\Models\Accounting\Contacts), false) #1 D:\MAMP\htdocs\xero-php-oauth2-custom-starter\vendor\xeroapi\xero-php-oauth2\lib\Api\AccountingApi.php(4349): XeroAPI\XeroPHP\Api\AccountingApi->createContactsWithHttpInfo('', Object(XeroAPI\XeroPHP\Models\Accounting\Contacts), false) #2 D:\MAMP\htdocs\xero-php-oauth2-custom-starter\authorizedResource.php(69): XeroAPI\XeroPHP\Api\AccountingApi->createContacts('', Object(XeroAPI\XeroPHP\Models\Accounting\Contacts)) #3 {main} thrown in D:\MAMP\htdocs\xero-php-oauth2-custom-starter\vendor\xeroapi\xero-php-oauth2\lib\Api\AccountingApi.php on line 4601_

**Comment by SerKnight** [comment]
Hey Jmd - a couple of questions. Do you have setup:
* A `.env` file with the custom credentials from your Xero API dashboard?
* Have Docker desktop running
* Docker Compose installed - https://docs.docker.com/compose/install/
* ran `composer install`
*Started the app using:
```
composer install
docker-compose up
```

**Comment by SerKnight** [comment]
The Error is related to MAMP which is how we used to encourage the setup for these sample apps, but I believe with the change to docker you no longer need to have MAMP running. I am double checking some things and will update if I can find any fixes to your issue. 

If you can confirm the following that would be helpful @jmd-david

**Comment by jmd-david** [comment]
Hi SerKnight thank you for taking time to reply on my post, i have fixed it by following the instruction on this page - https://github.com/XeroAPI/xero-php-oauth2/issues/240#issue-935388700

They have the same issue and downgrading of the guzzlehttp/psr7 to version 1.8 using the composer command:
composer require guzzlehttp/psr7 "^1.8" helps.

Thank you @SerKnight
